---

- dej:
    24:
        - 10.10.110.52:3com:five
        - 10.10.110.51:cisco:six
    48:
        - 10.10.110.56:cisco:seven
        - 10.10.110.(1,10,2):cisco:eight


#pridat sekvence hodnot
            
    
