#---
#- group: 
#    - name: dej
#    - interface:
#        - int5:
#            description: label
#            shutdown: no
            #vlan:
            #    mode: trunk
            #    allowed: a( 10  ,50  , 10)  
            #agregate:
            #    protocol: lacp
            #    channel: 1
            #    mode: negotiate
#        - int (  4, 10 , 2  ):
#                shutdown: yes


#- group:
#    - name: sin:48 

---
- interface:
    - int5:
#        description: label
        shutdown: no
    
#- vlan:
#    - vlan:
#        id: 100
 #       description: dej

