
---
#- group:
#    - name: cisco:cli
#    - interface:
#        - delete_int:
#            id: (2,24,1)
#        - int:
#            id: 15,5,18
#            vlan:
#                mode: trunk
#                allowed: 10
#            agregate:
 #               channel: 3
  #              mode: auto
#                protocol: pagp
#            shutdown: no
#    - vlan:
 #       - delete_vlan:
 #           id: 20,45,47,69,78,88,123,2,25,45,55,59,67,69,78,89,111,100
#            name: xxxVlanx
#        - int_vlan:
#            id: 78
#            description: intVlanint
#            ip: 4.2.3.5/30
#    - agregate:
#        - delete_channel:
#            id: (1,6,1)
#    - save:
#        - save_config:
#            id: 1

- group:
    - name: cisco:netconf
    - interface:
        - delete_int:
            id: 6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
            #description: automat
            #vlan:
            #    mode: access
            #    access: 10
