#---
#- group: 
#    - name: ssh
#    - interface:
#        - int(2,10,2):
#            description: AAAAAAAAAAAAAAAAAAAAAAAAAAAa
#            shutdown: no
#            vlan:
#                mode: trunk
#                allowed: 10
#            #agregate:
#            #    protocol: lacp
#            #    channel: 1
#            #    mode: negotiate
#        #- int9:
#        #    description: YYYYY
#        - delete_int:
#            id: (2,24,1)
#    - vlan:
#        - vlan:
#            id: 111
#            description: private
                
#- group:
#    - name: netconf
#    - interface:
#        - int5:
#           shutdown: no
    

#- group:
#    - name: sin:48 

#---
#- interface:
#    - int5:
#        description: label
#        shutdown: no
    
#- vlan:
#    - vlan:
#        id: 100
 #       description: dej

#delete vlan, interface - udelat volbu except


---
- group: 
    - name: ssl:ssh 
    - interface:
        - int:
            id: 10,11,12
            description: hello 
