---
- group: 
    - name: dej
    - vlan:
        - vlan100:
            description: guest
        - vlan200:
            description: admin

        - vlan:
            id: (10,50,10)
            description: user(10,40,10)X(z,v)
            #description50: management 
            #ip50: 192.168.1.1/24

    - group: 
        - name: 24
        - interface:
            - int2:
                shutdown: yes
    - group:
        - name: dalsi
        - vlan:
            - vlan10:
                description: pokus
    - interface:
        - int1:
            description: label
            shutdown: no
            vlan:
                mode: trunk
                allowed: 10,50,10  
            agregate:
                protocol: lacp
                channel: 1
                mode: negotiate
        - default:
            shutdown: no
            vlan:
                mode: access
                access: 20
                #!!pridat nativni vlan
        - mac: #nastavi vsechny krome vypsanejch
            id: 11:22:33:44:55:66
            vlan:
                mode: trunk
                allowed: 10, 20
            agregate:
                protocol: lacp
                channel: 1
                mode: on
        - mac: #nastavi vsechny krome vypsanejch
            id: "66:55:44:33:22:11"
            vlan:
                mode: trunk
        # pridat prepinac aby to nerozbalovalo tuty sekvenci //advanced
        - int(1,10,2):
                    shutdown: yes


- group:
    - name: sin:48 
