#---
#- group: 
#    - name: ssh
#    - interface:
#        - int(2,10,2):
#            description: AAAAAAAAAAAAAAAAAAAAAAAAAAAa
#            shutdown: no
#            vlan:
#                mode: trunk
#                allowed: 10
#            #agregate:
#            #    protocol: lacp
#            #    channel: 1
#            #    mode: negotiate
#        #- int9:
#        #    description: YYYYY
#        - delete_int:
#            id: (2,24,1)
#    - vlan:
#        - vlan:
#            id: 111
#            description: private
                
#- group:
#    - name: netconf
#    - interface:
#        - int5:
#           shutdown: no
    

#- group:
#    - name: sin:48 

#---
#- interface:
#    - int5:
#        description: label
#        shutdown: no
    
#- vlan:
#    - vlan:
#        id: 100
 #       description: dej

#delete vlan, interface - udelat volbu except


---
    #- interface:
    #    - int6:
    #        description: nazdar
- vlan:
    - vlan:
        id: 69
        description: pok69
        ip: 4.2.3.5/30
#- group:
#    - name: ssl:ssh2
#    - interface:
#        - int(12,15,1):
#            description: XXXXXXX
