---
- group: 
    - name: dejvicka
    - interface:
        - int1:
            #description: label
            #shutdown: no
            vlan:
                mode: trunk
                allowed: a( 10  ,50  , 10)  
            agregate:
                protocol: lacp
                channel: 1
                mode: negotiate
        - int (  1, 10 , 2  ):
                shutdown: yes


- group:
    - name: sin:48 
