################################################
# Author: Dominik Soukup, soukudom@fit.cvut.cz #
################################################
#---
#
#dej:
#    24:
#        - 10.10.110.231:cisco
#        - 10.10.110.230:cisco
#    48:
#        - 10.10.110.232:3com
#
#
#cisco  :
#    netconf   :
#        - 10.10.110.233:cisco
#    cli :
#        - 10.10.110.230:cisco
#        - 10.10.110.231:cisco
#_3com :
#    - 10.10.110.232:_3com
#
#    - 10.10.110.61:cisco
#
#netconf:
#    - 10.10.110.61:cisco
            
    
