---

dej:
    24:
        - 10.10.110.52:huawei
        - 10.10.110.51:cisco
    48:
        - 10.10.110.56:cisco
        - 10.10.110,111.(1,5,2):cisco

    53:
        - 10.10.110.1,2,3:3com
sin:
    24:
        - 10.10.110.40:cisco
        
#pridat sekvence hodnot
            
    
